Planning platform/Entities/Homework.cs
namespace Planning_platform.Entities
{
    public class Homework
    {
        public int Id { get; set; }
        //public int Plan_id { get; set; }
        public int? PlanId { get; set; } // Foreign key
        public Plan? Plan { get; set; } // Reference navigation
        public string Text { get; set; }
    }
}

Planning platform/Controllers/HomeworksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Planning_platform.Data;
using Planning_platform.Entities;
using Planning_platform.Migrations;

namespace Planning_platform.Controllers
{
    public class HomeworksController : Controller
    {
        private readonly ApplicationDbContext _context;
        RoleManager<IdentityRole> _roleManager;
        UserManager<ApplicationUser> _userManager;
        public HomeworksController(ApplicationDbContext context, RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        // GET: Homework
        [Authorize(Roles = "teacher")]

        public async Task<IActionResult> Index()
        {

            DateTime nowDate = new DateTime(2023, 9, 1);
            DateTime lastDate = nowDate.AddDays(7);
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var lessons = _context.Lessons.Include(l => l.Class).Include(l => l.Subject).Include(l => l.Plans).Where(p => p.Teacher.Id==user.Id).ToList();
            foreach (var lesson in lessons)
            {
                var tempPlans = new List<Plan>(lesson.Plans);
                foreach (var plan in tempPlans)
                {
                    if (plan.Date > lastDate)
                    {
                        lesson.Plans.Remove(plan);
                    }

                }
            }
            var orderedLessons = from p in lessons orderby p.Number_on_day select p;


            var applicationDbContext = _context.Homeworks.Include(h => h.Plan);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Homework/Details/5
        [Authorize(Roles = "teacher")]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Homeworks == null)
            {
                return NotFound();
            }

            var homework = await _context.Homeworks
                .Include(h => h.Plan)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (homework == null)
            {
                return NotFound();
            }

            return View(homework);
        }

        // GET: Homework/Create
        [Authorize(Roles = "teacher")]

        public IActionResult Create()
        {
            ViewData["PlanId"] = new SelectList(_context.Plans, "Id", "Id");
            return View();
        }

        // POST: Homework/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "teacher")]

        public async Task<IActionResult> Create([Bind("Id,PlanId,Text")] Homework homework)
        {
            if (ModelState.IsValid)
            {
                _context.Add(homework);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PlanId"] = new SelectList(_context.Plans, "Id", "Id", homework.PlanId);
            return View(homework);
        }

        // GET: Homework/Edit/5
        [Authorize(Roles = "teacher")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Homeworks == null)
            {
                return NotFound();
            }

            var homework = await _context.Homeworks.FindAsync(id);
            if (homework == null)
            {
                return NotFound();
            }
            ViewData["PlanId"] = new SelectList(_context.Plans, "Id", "Id", homework.PlanId);
            return View(homework);
        }

        // POST: Homework/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "teacher")]

        public async Task<IActionResult> Edit(int id, [Bind("Id,PlanId,Text")] Homework homework)
        {
            homework.Plan = null;
            if (id != homework.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(homework);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HomeworkExists(homework.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PlanId"] = new SelectList(_context.Plans, "Id", "Id", homework.PlanId);
            return View(homework);
        }

        // GET: Homework/Delete/5
        [Authorize(Roles = "teacher")]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Homeworks == null)
            {
                return NotFound();
            }

            var homework = await _context.Homeworks
                .Include(h => h.Plan)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (homework == null)
            {
                return NotFound();
            }

            return View(homework);
        }

        // POST: Homework/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "teacher")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Homeworks == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Homeworks'  is null.");
            }
            var homework = await _context.Homeworks.FindAsync(id);
            if (homework != null)
            {
                _context.Homeworks.Remove(homework);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "teacher")]

        private bool HomeworkExists(int id)
        {
          return (_context.Homeworks?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Planning platform/Controllers/PlansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Office.Interop.Excel;
using NuGet.Versioning;
using Planning_platform.Data;
using Planning_platform.Entities;
using Planning_platform.Models;

using Planning_platform.Migrations;
using System.Linq;
using System.Numerics;
using Microsoft.AspNetCore.Authorization;

namespace Planning_platform.Controllers
{
    public class PlansController : Controller
    {
        private readonly ApplicationDbContext _context;
        RoleManager<IdentityRole> _roleManager;
        UserManager<ApplicationUser> _userManager;
        public PlansController(ApplicationDbContext context, RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        // GET: Plans
        [Authorize(Roles = "teacher")]

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            var applicationDbContext = _context.Plans.Include(p => p.Lesson).Where(l=>l.Lesson.Teacher.Id==user.Id);

            

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Plans/Details/5
        [Authorize(Roles = "teacher")]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Plans == null)
            {
                return NotFound();
            }

            var plan = await _context.Plans
                .Include(p => p.Lesson)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (plan == null)
            {
                return NotFound();
            }

            return View(plan);
        }

        // GET: Plans/Create
        [Authorize(Roles = "teacher")]

        public async Task<IActionResult> Create()
        {
            // Загрузить файл Excel
            var wb = new Aspose.Cells.Workbook("C:\\Users\\user\\Desktop\\математика 7 класс.xlsx");
            var collection = wb.Worksheets;
            for (int worksheetIndex = 0; worksheetIndex < collection.Count; worksheetIndex++)
            {
                var worksheet = collection[worksheetIndex];
                int rows = worksheet.Cells.MaxDataRow;
                int cols = worksheet.Cells.MaxDataColumn;
                List<Plan> plans = new List<Plan>();
                List<Homework> homeworks = new List<Homework>();

                var user = await _userManager.GetUserAsync(HttpContext.User);
                List<Lesson> lessons = _context.Lessons.Include(p => p.Subject).Include(p => p.Class).ToList().Where(p => p.ClassId == 1004).Where(p=>p.SubjectId==1).ToList();
                int allLessonsCounter = 0;
                var i = 3;
                //var j = 3;
                int maxLessonsCounter = (int)worksheet.Cells[rows, 0].Value;
                List<int> hours = new List<int>();
                //DateTime dateValue = new DateTime(2023, 9, 1);
                //int lessonsCounterForDate = 0;
                List<DateTime> dates = new List<DateTime>();
                DateTime firstDay = new DateTime(2023, 9, 1);
                var dayOfWeek = (int)firstDay.DayOfWeek;//1,2,3,4,5
                //while (dayOfWeek > 5||dayOfWeek==0)
                //{
                //    firstDay=firstDay.AddDays(1);
                //    dayOfWeek = (int)firstDay.DayOfWeek;//1,2,3,4,5
                //}
                ////var currLesson = lessons[dayOfWeek - 1];

                //firstDay = firstDay.AddDays(1);

                //lessonsCounterpozitionForDays
                //plan.LessonId = lessons[pozition].Id;


                //Console.WriteLine(dateValue.ToString("dddd"));
                int chapter =0;
                int lessonsCounter = dayOfWeek - 1;
                while (true)
                {
                    var cell = worksheet.Cells[i, 3].Value;
                    
                    if (cell == null)
                    {
                        i++;
                        continue;
                    }
                    var homeworkReaded = worksheet.Cells[i, 6].Value;
                    var strHomework = (string)homeworkReaded;
                    var hoursValue = (int)cell;

                    hours.Add(hoursValue);
                    i += hoursValue;

                    allLessonsCounter += hoursValue;
                    try
                    {
                        var firstNumstr = strHomework.Substring(strHomework.IndexOf('№') + 1, strHomework.IndexOf('-') - 1);
                        chapter = Int32.Parse(firstNumstr.Substring(0, firstNumstr.IndexOf('.')));
                        int firstNum = Int32.Parse(firstNumstr.Substring(firstNumstr.IndexOf('.') + 1));

                        var lastNumstr = strHomework.Substring(strHomework.IndexOf('-') + 1);
                        int lastNum = Int32.Parse(lastNumstr.Substring(lastNumstr.IndexOf('.') + 1));

                        int step = (lastNum - firstNum) / hoursValue;

                        int firstNumOfHomework = firstNum;
                        while (firstNumOfHomework <= lastNum - step - step)
                        {
                            if(firstDay>=new DateTime(2023,10,29)&& firstDay <= new DateTime(2023, 11, 7))
                            {
                                firstDay = new DateTime(2023, 11, 8);
                            }

                            dayOfWeek = (int)firstDay.DayOfWeek;//1,2,3,4,5

                            while (dayOfWeek > 5 || dayOfWeek == 0)
                            {
                                firstDay = firstDay.AddDays(1);
                                dayOfWeek = (int)firstDay.DayOfWeek;//1,2,3,4,5
                            }
                            //var currLesson = lessons[dayOfWeek - 1];
                            if (firstDay >= new DateTime(2023, 10, 29) && firstDay <= new DateTime(2023, 11, 7))
                            {
                                firstDay = new DateTime(2023, 11, 8);
                            }

                            dayOfWeek = (int)firstDay.DayOfWeek;//1,2,3,4,5

                            Plan plan = new Plan();
                            int pozition = (dayOfWeek-1) % lessons.Count;
                            lessonsCounter++;
                            plan.LessonId = lessons[pozition].Id;
                            plan.Date = firstDay;//new DateTime(2023, 9, 1);
                            firstDay = firstDay.AddDays(1);

                            _context.Add(plan);
                            await _context.SaveChangesAsync();
                            var planId= _context.Plans.ToList()[_context.Plans.ToList().Count-1].Id;

                            Homework homework = new Homework();
                            string homeworkString = "№" + chapter.ToString() + '.' + firstNumOfHomework.ToString() + " - " + chapter.ToString() + '.' + (firstNumOfHomework + step - 1).ToString();
                            homework.Text = homeworkString;
                            homework.PlanId = planId;
                            homeworks.Add(homework);
                            firstNumOfHomework += step;
                            _context.Add(homework);
                            await _context.SaveChangesAsync();



                            //firstNumOfHomework += 1;
                        }
                        if (firstDay >= new DateTime(2023, 10, 29) && firstDay <= new DateTime(2023, 11, 7))
                        {
                            firstDay = new DateTime(2023, 11, 8);
                        }
                        dayOfWeek = (int)firstDay.DayOfWeek;//1,2,3,4,5
                        while (dayOfWeek > 5 || dayOfWeek == 0)
                        {
                            firstDay = firstDay.AddDays(1);
                            dayOfWeek = (int)firstDay.DayOfWeek;//1,2,3,4,5
                        }
                        Plan planLast = new Plan();
                        int pozitionLast = (dayOfWeek - 1) % lessons.Count;
                        lessonsCounter++;
                        planLast.LessonId = lessons[pozitionLast].Id;
                        planLast.Date = firstDay;//new DateTime(2023, 9, 1);
                        firstDay = firstDay.AddDays(1);

                        firstDay = firstDay.AddDays(1);
                        _context.Add(planLast);
                        await _context.SaveChangesAsync();
                        var planIdLast = _context.Plans.ToList()[_context.Plans.ToList().Count - 1].Id;

                        Homework homeworkLast = new Homework();
                        string homeworkStr = "№" + chapter.ToString() + '.' + firstNumOfHomework.ToString() + " - " + chapter.ToString() + '.' + (lastNum).ToString();
                        homeworkLast.Text = homeworkStr;
                        homeworkLast.PlanId = planIdLast;
                        homeworks.Add(homeworkLast);
                        _context.Add(homeworkLast);
                        await _context.SaveChangesAsync();


                    }
                    catch
                    {
                        if (firstDay >= new DateTime(2023, 10, 29) && firstDay <= new DateTime(2023, 11, 7))
                        {
                            firstDay = new DateTime(2023, 11, 8);
                        }
                        dayOfWeek = (int)firstDay.DayOfWeek;//1,2,3,4,5
                        while (dayOfWeek > 5 || dayOfWeek == 0)
                        {
                            firstDay = firstDay.AddDays(1);

Planning platform/Views/Homeworks/Create.cshtml
@model Planning_platform.Entities.Homework

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Создание</h1>

<h4>Домашнего задания</h4>
<hr />
Вы не можете так создать домашнее задание.
@* <div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PlanId" class="control-label"></label>
                <select asp-for="PlanId" class ="form-control" asp-items="ViewBag.PlanId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div> *@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Planning platform/Views/Homeworks/Delete.cshtml
@model Planning_platform.Entities.Homework

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Удаление</h1>

<h3>Вы уверены, что хотите удалить это домашнее задание?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Текст        
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

Planning platform/Views/Homeworks/Details.cshtml
@model Planning_platform.Entities.Homework

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Просмотр</h1>

<div>
    <h4>Домашнего задания</h4>
    <hr />
    <dl class="row">
@*         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plan.Id)
        </dd> *@
        <dt class = "col-sm-2">
            Текст
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Редактировать</a> |
    <a asp-action="Index">Вернуться к списку</a>
</div>

Planning platform/Views/Homeworks/Edit.cshtml
@model Planning_platform.Entities.Homework

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Редактирование</h1>

<h4>Домашнего задания</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="hidden" asp-for="PlanId" />
@*                 <label asp-for="PlanId" class="control-label">План</label>
                <select asp-for="PlanId" class="form-control" asp-items="ViewBag.PlanId" type="hidden"></select>
                <span asp-validation-for="PlanId" class="text-danger"></span> *@
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label">Текст</label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Planning platform/Views/Homeworks/Index.cshtml
@model IEnumerable<Planning_platform.Entities.Homework>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Домашние задания</h1>

<p>
    <a asp-action="Create" asp-controller="Plans">Создать новое планирование</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Предмет
            </th>
            <th>
                Текст
            </th>
            <th>
                Дата
            </th>
            <th>
                Класс
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    if(item.Plan.Lesson!=null){
        @if(item.Plan.Lesson.Subject!=null){
            @if(item.Plan.Lesson.Subject.Subject_name!=null){
                <tr>
                    <td>
                        @item.Plan.Lesson.Subject.Subject_name
                    </td>

                    <td>
                        @item.Text
                    </td>
                <td>
                    @item.Plan.Date.ToShortDateString()
                </td>
                <td>
                    @item.Plan.Lesson.Class.FullName
                </td>


            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редактировать</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Просмотреть</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>

        </tr>
                               }}
        }}
    </tbody>
</table>